#!/bin/bash
export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

# prerequisites:
for pkg in gpg rng-tools sudo; do
  if [ -z "${pkg}" ]; then
      echo "Cannot find ${pkg} in path. Aborting"
      exit 1;
  fi
done

DNSDOMAINNAME=$(dnsdomainname)
if [ -z "${DNSDOMAINNAME}" ]; then
  echo "dnsdomainname returns an empty domain"
  exit 1;
fi

SECRET=$(cat ~/.secret)
if [ -z "${SECRET}" ]; then
  echo "secret is empty"
  exit 1;
fi

PACKAGE_USER='packagemaster'
PACKAGE_HOST="apt.${DNSDOMAINNAME}"

gpg --list-keys|grep -q "^uid *${PACKAGE_USER}@${PACKAGE_HOST}"
if [ $? -eq 0 ];then
    logger -p local5.error -- "$0[$$] apt keys already exists. Aborting..."
    exit 0
fi
if [ -z ${SECRET} ];then
    logger -p local5.error -- "$0[$$] environment SECRET not set. Aborting..."
    exit 1
fi

PREUMASK=$(umask)
umask 0377
TMPFILE=$(mktemp /dev/shm/gpg-genkey.XXXXX)
/bin/cat<<EOF>${TMPFILE}
%echo Generating a package signing key
Key-Type: DSA
Key-Length: 1024
Subkey-Type: ELG-E
Subkey-Length: 2048
Name-Real:  ${PACKAGE_HOST}
Name-Email: ${PACKAGE_USER}@${PACKAGE_HOST}
Expire-Date: 0
Passphrase: ${SECRET}
%commit
%echo Done
EOF
umask ${PREUMSK}
# /bin/ps -ef | /bin/grep -q "rn[g]d " || sudo /usr/sbin/rngd -r /dev/urandom
# (find / -xdev -type f -exec sha256sum {} >/dev/null \; 2>&1) &
gpg --batch --gen-key ${TMPFILE} > /var/log/gpg-keygen.log 2> /var/log/gpg-keygen_error.log
rm ${TMPFILE}

